export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const INIT_BURGER = 'INIT_BURGER';
export const INIT_BURGER_FAIL = 'INIT_BURGER_FAIL';


export const ORDER_START='ORDER_START';
export const ORDER_OK='ORDER_OK';
export const ORDER_FAIL='ORDER_FAIL';
export const PURCHASE_START='PURCHASE_START';