export const ADD_INGREDIENT ='ADD_INGREDIENT';
export const REMOVE_INGREDIENT ='REMOVE_INGREDIENT';
export const INIT_INGREDIENT ='INIT_INGREDIENT';
export const FETCH_FAILED ='FETCH_FAILED';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_SUCESS =  'PURCHASE_SUCESS';
export const PURCHASE_FAIL =  'PURCHASE_FAIL';


export const ORDER_FETCH_START = 'ORDER_FETCH_START';
export const ORDER_FETCH_SUCESS =  'ORDER_FETCH_SUCESS';
export const ORDER_FETCH_FAIL =  'ORDER_FETCH_FAIL';
